# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-10 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=50)),
                ('registry_no', models.CharField(max_length=100)),
                ('property_pic', models.CharField(max_length=1000)),
                ('property_type', models.CharField(max_length=50)),
                ('property_style', models.CharField(max_length=50)),
                ('property_region', models.CharField(max_length=50)),
                ('Age', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=5)),
                ('no_of_kitchen', models.CharField(max_length=5)),
                ('no_of_bedroom', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='HouseAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=50)),
                ('sec', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.House')),
            ],
        ),
        migrations.CreateModel(
            name='HouseOwnerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=2000)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.House')),
            ],
        ),
    ]
