# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-11 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='year_built',
            field=models.CharField(default=1990, max_length=5),
        ),
    ]
