# Generated by Django 2.0.1 on 2018-10-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20181011_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseownerdetails',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='house',
            name='property_pic',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
